AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LectureFlow API - FastAPI on Lambda (Container)

Globals:
  Function:
    Timeout: 300
    MemorySize: 1024

Parameters:
  GeminiApiKey:
    Type: String
    NoEcho: true
  OpenaiApiKey:
    Type: String
    NoEcho: true
  ElevenlabsApiKey:
    Type: String
    NoEcho: true
  DatabaseUrl:
    Type: String
    NoEcho: true
  AllowedOrigins:
    Type: String
    Default: "*"

Resources:
  LectureFlowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lectureflow-api
      PackageType: Image
      ImageUri: 114059502095.dkr.ecr.us-east-1.amazonaws.com/lectureflow-api:latest
      Architectures:
        - x86_64
      Environment:
        Variables:
          GEMINI_API_KEY: !Ref GeminiApiKey
          OPENAI_API_KEY: !Ref OpenaiApiKey
          ELEVENLABS_API_KEY: !Ref ElevenlabsApiKey
          DATABASE_URL: !Ref DatabaseUrl
          ALLOWED_ORIGINS: !Ref AllowedOrigins
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
